#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import subprocess
import samba

request = json.load(sys.stdin)
user = request['user']
groups = request.get('groups', [])
password = request.get('password', '') # Empty string implies a random password is set
display_name = request.get('display_name', '')
locked = request.get('locked', False)
mail = request.get('mail', '')
phone_extension = request.get('phone_extension', '')

sambatool_cmd = ['podman', 'exec', '-i', 'samba-dc', 'samba-tool']
adduser_cmd = sambatool_cmd + ['user', 'create', user]
if request.get('must_change_password') == True:
    adduser_cmd += ['--must-change-at-next-login']

if not password:
    adduser_cmd += ['--random-password']
    inputdata = None
else:
    inputdata = password + "\n" + password + "\n"

subprocess.run(adduser_cmd, input=inputdata, stdout=sys.stderr, check=True, text=True)

if locked:
    lock_cmd = sambatool_cmd + ['user', 'disable', user]
    subprocess.run(lock_cmd, stdout=sys.stderr, check=True, text=True)

for group in groups:
    addmember_cmd = sambatool_cmd + ['group', 'addmembers', group, user]
    subprocess.run(addmember_cmd, stdout=sys.stderr, check=True, text=True)

if display_name:
    setname_cmd = ['podman', 'exec', '-i', 'samba-dc', 'pdbedit', '-u', user, f'--fullname={display_name}']
    subprocess.run(setname_cmd, stdout=sys.stderr, check=True, text=True)

if mail:
    samba.set_or_clear_ldap_attribute(user, 'mail', mail)

if phone_extension:
    samba.set_or_clear_ldap_attribute(user, 'telephoneNumber', phone_extension)

if "no_password_expiration" in request:
    dn_str, user_account_control = samba.get_user_account_control(user)
    samba.set_user_account_control(dn_str, user_account_control, request['no_password_expiration'])
