#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import agent
import json
import samba

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

try:
    samba.ipaddress_check_hasfreeports('127.0.0.1')
except samba.IpBindError as ex:
    print(ex, file=sys.stderr)
    agent.set_status('validation-failed')
    json.dump([{"field":"ipaddress","parameter":"ipaddress","value": ex.ipaddr,"error":"ipaddress_bind_check_failed"}], fp=sys.stdout)
    sys.exit(4)
