#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

exec 1>&2
set -e

readarray -t input < <(jq -r '.adminuser, .adminpass')

tmpenv=$(mktemp)
trap "rm -f ${tmpenv}" EXIT

(
    echo JOINADDRESS=$(print-joinaddress 2>/dev/null || :)
    echo -n "ADMINCREDS="
    echo -en "${input[0]:?}"$'\t'"${input[1]:?}" | base64
) > ${tmpenv}

/usr/bin/podman run \
    --dns=none \
    --no-hosts \
    --network=host \
    --privileged \
    --interactive \
    --env=REALM \
    --env=IPADDRESS \
    --env=PREFIXLEN \
    --env=NBDOMAIN \
    --env=SVCPASS \
    --env=SVCUSER \
    --env-file=${tmpenv} \
    --hostname=${HOSTNAME:?} \
    --log-driver=none \
    --rm --name=${MODULE_ID}-provision \
    --volume=data:/var/lib/samba:z \
    --volume=config:/etc/samba:z \
    "${SAMBA_DC_IMAGE:?}" "${PROVISION_TYPE:?}"
