#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import agent.tasks
import os
import sys
import json
import ipaddress as ipm

#
# Check if routes for this new DC must be added automatically
#

realm = os.environ['REALM']
node_id = int(os.environ['NODE_ID'])

rdb = agent.redis_connect()

oip_address = ipm.ip_address(os.environ['IPADDRESS'])
ocluster_network = ipm.ip_network(rdb.get('cluster/network'), strict=False)

if not oip_address in ocluster_network:
    update_routes_result = agent.tasks.run(
        agent_id='cluster',
        action='update-routes',
        data={
            'add': [{
                "ip_address": os.environ['IPADDRESS'],
                "node_id": node_id,
            }],
        },
    )
    agent.assert_exp(update_routes_result['exit_code'] == 0)
