#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This script is linked to
# - configure-module
# - update-module.d/

import agent
import sys
import os
import json

rdb = agent.redis_connect()
module_id = os.environ["MODULE_ID"]
has_file_server_flag = bool(rdb.sismember(f'module/{module_id}/flags', 'file_server'))
if has_file_server_flag:
    domain = os.environ['REALM'].lower()
    agent.bind_user_domains([domain], check=False)
else:
    agent.bind_user_domains([], check=False)
