#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import agent
import json
import subprocess

request = json.load(sys.stdin)
group = request['group']
users = request['users']
description = request.get('description', '')

testexists_cmd = ['podman', 'exec', '-i',
                  'samba-dc', 'samba-tool', 'group', 'show', group]
proc = subprocess.run(testexists_cmd, stdout=subprocess.DEVNULL,
                      stderr=subprocess.DEVNULL, text=True)
if proc.returncode == 0:
    json.dump({"status": "failure", "message": "", "error": [
              {'field': 'group', 'parameter': 'group', 'value': group, 'error': 'group_already_exists'}]}, fp=sys.stdout)
    sys.exit(2)

addgroup_cmd = [
    'podman', 'exec', 'samba-dc', 'samba-tool',
    'group', 'add', group
]

if description:
    addgroup_cmd += ['--description=' + description]

subprocess.run(addgroup_cmd, stdout=sys.stderr, check=True, text=True)

if users:
    addmembers_cmd = [
        'podman', 'exec', 'samba-dc', 'samba-tool',
        'group', 'addmembers', group, ','.join(users),
    ]

    subprocess.run(addmembers_cmd, stdout=sys.stderr, check=True, text=True)

json.dump({"status": "success", "message": "group_created"}, fp=sys.stdout)
