#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import agent
import json
import subprocess

request = json.load(sys.stdin)
group = request['group']
users = request['users']
description = request.get('description', '')

testexists_cmd = ['podman', 'exec', '-i',
                  'samba-dc', 'samba-tool', 'group', 'show', group]
proc = subprocess.run(testexists_cmd, stdout=subprocess.DEVNULL,
                      stderr=subprocess.DEVNULL, text=True)
if proc.returncode == 0:
    json.dump({"status": "failure", "message": "", "error": [
              {'field': 'group', 'parameter': 'group', 'value': group, 'error': 'group_already_exists'}]}, fp=sys.stdout)
    sys.exit(2)

addgroup_cmd = [
    'podman', 'exec', 'samba-dc', 'samba-tool',
    'group', 'add', group
]

if description:
    addgroup_cmd += ['--description=' + description]

subprocess.run(addgroup_cmd, stdout=sys.stderr, check=True, text=True)

if users:
    addmembers_cmd = [
        'podman', 'exec', 'samba-dc', 'samba-tool',
        'group', 'addmembers', group, ','.join(users),
    ]

    subprocess.run(addmembers_cmd, stdout=sys.stderr, check=True, text=True)

json.dump({"status": "success", "message": "group_created"}, fp=sys.stdout)
