#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import subprocess
import os

request = json.load(sys.stdin)
group = request['group']
users = request['users']
description = request.get('description', '')

addgroup_cmd = [
    'podman', 'exec', os.environ['MODULE_ID'], 'samba-tool',
    'group', 'add', group
]

if description:
    addgroup_cmd += ['--description=' + description]

subprocess.run(addgroup_cmd, stdout=sys.stderr, check=True, text=True)

if users:
    addmembers_cmd = [
        'podman', 'exec', os.environ['MODULE_ID'], 'samba-tool',
        'group', 'addmembers', group, ','.join(users),
    ]

    subprocess.run(addmembers_cmd, stdout=sys.stderr, check=True, text=True)
