#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Create the shares root directory and set permissions on it. Home dirs
# and shared folders are created under this root directory.
#

set -e

: ${SAMBA_SHARES_DIR:?shares directory is not defined}

mkdir -vp "${SAMBA_SHARES_DIR}"
chown -c root:administrators "${SAMBA_SHARES_DIR}"
chmod -c 0770 "${SAMBA_SHARES_DIR}"

if ! getfattr -n user.NTACL "${SAMBA_SHARES_DIR}" &>/dev/null; then
    # FULL access to Administrator user and "Builtin Administrators" (BA -- Domain Admins) group
    samba-tool ntacl set 'O:LAG:BAD:PAI(A;OI;0x001f01ff;;;SY)(A;OI;0x001f01ff;;;BA)' "${SAMBA_SHARES_DIR}"
fi
