#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

usage_error ()
{
    exec 1>&2
    [ -n "$1" ] && printf "Error: %s\n" "$1"
    printf 'Usage: %s [OPTIONS] SHARE\n' "$0"
    printf '    SHARE                   Create a shared folder\n'
    printf '    OPTIONS\n'
    printf '      -d description        Share description\n'
    printf '      -p PERMS              Permissions, one of: erw, ergrw, grw (default)\n'
    printf '      -g group              Target group name, default "%s"\n' "${group_name}"
    printf '      -h                    Print this help\n'
    exit 2
}

# Default option values:
description=
group_name="domain users"
perms=grw

# Parse command-line arguments
while getopts "hd:g:p:" optname ; do
    case ${optname} in
        p)  perms="${OPTARG}" ;;
        d)  description="${OPTARG}" ;;
        g)  group_name="${OPTARG}" ;;
        h)  usage_error "${@}" ;;
        *)  usage_error "${@}" ;;
    esac
done
shift $((OPTIND - 1))

sharename="${1}"
[ -z "${sharename}" ] && usage_error "${@}"

share_root="${SAMBA_SHARES_DIR}/${sharename}"

# drop the sharename argument
shift

if [[ -e "${share_root}" ]]; then
    echo "Directory ${sharename} already exists!" 1>&2
    exit 2
fi

if ! wbinfo --group-info "${group_name}" &>/dev/null ; then
    echo "Group ${group_name} not found!" 1>&2 
    exit 3
fi

mkdir -vp "${share_root}"
chmod -c 0775 "${share_root}"
chown -c "root:users" "${share_root}"

net conf addshare "${sharename}" "${share_root}" writeable=y guest_ok=n "${description}"

exec samba-reset-acls -p "${perms}" -g "${group_name}" "${sharename}"
