#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

sharename="${1:?missing sharename argument}"

share_path="${SAMBA_SHARES_DIR}/${sharename}"

net conf delshare "${sharename}" &>/dev/null || : # Ignore failure for home dirs

if ! [[ -d "${share_path}" ]]; then
    echo "Directory ${sharename} not found" 1>&2
    exit 2
fi

rm -rf "${share_path}"
