#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

sharename="${1:?missing sharename argument}"

share_path="/var/lib/samba/shares/${sharename}"

net conf delshare "${@}" || : # Ignore failure for home dirs

rm -rf "${share_path}"
