#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient
import agent
import os

request = json.load(sys.stdin)

domain = Ldapproxy().get_domain(os.environ['REALM'].lower())

users = Ldapclient.factory(**domain).list_users()

users = sorted(users, key=lambda rec: rec['user'])

json.dump({"status": "success", "message": "users_listed", "users": users}, fp=sys.stdout)