#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient
import agent
import os

request = json.load(sys.stdin)

domain = Ldapproxy().get_domain(os.environ['REALM'].lower())

groups = Ldapclient.factory(**domain).list_groups()

groups = sorted(groups, key=lambda rec: rec['group'].lower())

json.dump({"status": "success", "message": "groups_listed", "groups": groups}, fp=sys.stdout)
