#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import subprocess
import configparser

podman_exec = ["podman", "exec", "samba-dc"]
nbdomain = os.environ["NBDOMAIN"]

def read_acls(share_name):
    """
    Parse smbcacls output and translate it to our simple ACLs format
    """
    pacls = subprocess.run(
        podman_exec + ["smbcacls", "-P", "//127.0.0.1/" + share_name, ""],
        text=True, stdout=subprocess.PIPE)
    if pacls.returncode != 0:
        return [] # The command has failed

    acls = []
    def subject_index(subject_name):
        """
        Return the index in the acls array of the first ACL with
        subject_name. If the subject is not found return -1
        """
        for idx, acl in enumerate(acls):
            if acl["subject"] == subject_name:
                return idx

        return -1

    for iline in filter(None, pacls.stdout.split("\n")):
        ifields = iline.split(":")
        if ifields[0] != "ACL":
            continue # Consider only ACL entries

        subject_name = ifields[1].removeprefix(nbdomain + "\\")
        ace_type, _, ace_rights = ifields[2].split("/", 2)

        if ace_type != "ALLOWED":
            rights = "special"
        elif ace_rights == "FULL":
            rights = "full"
        elif ace_rights == "READ":
            rights = "ro"
        elif ace_rights == "RWXD":
            rights = "rw"
        else:
            rights = "special"

        idx = subject_index(subject_name)
        if idx >=0:
            # Multiple entries for the same subject are forced to rights=special
            # We use the index to preserve the ordering returned by smbcacls
            acls[idx]["rights"] = "special"
        else:
            # New subject, assign rights
            acls.append({"subject": subject_name, "rights": rights})

    return acls

list_shares = {
    "shares": []
}

ocfg = configparser.ConfigParser(delimiters=("="))
with subprocess.Popen(podman_exec + ["net", "conf", "list"], stdout=subprocess.PIPE, text=True) as hconf:
    try:
        ocfg.read_file(hconf.stdout, 'samba-registry-conf')
    except Exception as ex:
        print(agent.SD_ERR + "Share configuration parse error", ex, file=sys.stderr)

psharenames = subprocess.run(podman_exec + ["net", "conf", "listshares"], stdout=subprocess.PIPE, text=True)
for share_name in filter(None, psharenames.stdout.split("\n")):
    comment = ocfg.get(share_name, "comment") or ""

    list_shares['shares'].append({
        "name": share_name,
        "description": comment,
        "acls": read_acls(share_name),
    })

json.dump(list_shares, fp=sys.stdout)