#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import subprocess
import os

request = json.load(sys.stdin)
group = request['group']

removegroup_cmd = [
    'podman', 'exec', 'samba-dc', 'samba-tool',
    'group', 'delete', group,
]

subprocess.run(removegroup_cmd, stdout=sys.stderr, check=True, text=True)

json.dump({"status": "success", "message": "group_removed"}, fp=sys.stdout)
