#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

podman_exec = ["podman", "exec", "samba-dc"]

request = json.load(sys.stdin)

samba_remove_share = podman_exec + ["samba-remove-share", request["name"]]

phelper = agent.run_helper(*samba_remove_share)
if phelper.returncode == 0:
    pass
elif phelper.returncode == 2:
    agent.set_status('validation-failed')
    json.dump([{'field':'name', 'parameter':'name','value': request['name'], 'error':'share_not_found'}], fp=sys.stdout)
    sys.exit(2)
else:
    phelper.check_returncode()
