#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import sys
import json
import agent



event = json.load(sys.stdin)
if not os.environ["REALM"].lower() in [domain.lower() for domain in event["domains"]]:
    sys.exit(0)

agent.run_helper('systemctl', '--user', 'try-reload-or-restart', 'samba-dc.service').check_returncode()
