#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import sys
import json
import agent



event = json.load(sys.stdin)
domain = os.environ["REALM"].lower()
if not domain in event["domains"]:
    sys.exit(0)

agent.run_helper('write-user-portal-config')
