#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

agent.assert_exp(agent.add_public_service(os.environ['MODULE_ID'], [
    "53/tcp", "53/udp", # DNS
    "88/tcp", "88/udp", # Kerberos
    "123/udp", # NTP
    "135/tcp", # End Point Mapper (DCE/RPC Locator Service)
    "137/udp", # NetBIOS Name Service
    "138/udp", # NetBIOS Datagram
    "139/tcp", # NetBIOS Session 
    "389/tcp", "389/udp", # LDAP
    "445/tcp", # SMB over TCP
    "464/tcp", "464/udp", # Kerberos kpasswd
    "636/tcp", # LDAPS
    "3268/tcp", # Global Catalog
    "3269/tcp", # Global Catalog SSL
    "49152-65535/tcp" # Dynamic RPC Ports
    ]))
