#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e 

exec 1>&2 # send any output to stderr
#
# Do not demote if instance has any FSMO role
#

podman exec -ti samba-dc validate-demote
