#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

#
# Try to demote the DC
#

user=$(cat /dev/stdin | jq -r '.adminuser // empty')
password=$(cat /dev/stdin | jq -r '.adminpass // empty')
echo "$password" | podman exec -ti samba-dc samba-tool domain demote -U"$user"
