#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import subprocess
import os
import samba

request = json.load(sys.stdin)
user = request['user']

sambatool_cmd = ['podman', 'exec', '-i', 'samba-dc', 'samba-tool']

if 'password' in request:
    password = request['password']
    must_change_password = request.get('must_change_password', False)  # If 'must_change_password' is True, the user must change their password at next login
    inputdata = password + "\n" + password + "\n"
    setpassword_cmd = sambatool_cmd + ['user', 'setpassword', user]
    if must_change_password:
        setpassword_cmd += ['--must-change-at-next-login']
    subprocess.run(setpassword_cmd, input=inputdata, stdout=sys.stderr, check=True, text=True)

if 'no_password_expiration' in request:
    dn_str, user_account_control = samba.get_user_account_control(user)
    samba.set_user_account_control(dn_str, user_account_control, request['no_password_expiration'])

if 'locked' in request:
    if request['locked'] == True:
        setenabled_cmd = sambatool_cmd + ['user', 'disable', user]
    else:
        setenabled_cmd = sambatool_cmd + ['user', 'enable', user]

    subprocess.run(setenabled_cmd, stdout=sys.stderr, check=True, text=True)

if 'groups' in request:
    # Calculate differences between old and new group sets,
    # then iterate over each group to add/remove the user from it.

    new_groups = set(request['groups'])
    getgroups_cmd = sambatool_cmd + ['user', 'getgroups', user]
    with subprocess.Popen(getgroups_cmd, stdout=subprocess.PIPE, text=True) as proc:
        old_groups = set(proc.stdout.read().strip().split("\n"))

    old_groups -= {'Domain Users'} # This group is always set, ignore it!

    add_groups = new_groups - old_groups
    for group in add_groups:
        subprocess.run(sambatool_cmd + ['group', "addmembers", group, user], stdout=sys.stderr, check=True, text=True)

    rem_groups = old_groups - new_groups
    for group in rem_groups:
        subprocess.run(sambatool_cmd + ['group', "removemembers", group, user], stdout=sys.stderr, check=True, text=True)

if 'display_name' in request:
    display_name = request['display_name']
    setname_cmd = ['podman', 'exec', '-i', 'samba-dc', 'pdbedit', '-u', user, f'--fullname={display_name}']
    subprocess.run(setname_cmd, stdout=sys.stderr, check=True, text=True)

if 'mail' in request:
    samba.set_or_clear_ldap_attribute(user, 'mail', request['mail'], check=False)

if 'phone_extension' in request:
    samba.set_or_clear_ldap_attribute(user, 'telephoneNumber', request['phone_extension'], check=False)
