#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import os
import agent
import agent.tasks

# Clean up Traefik route for amld user portal:
agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='delete-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-amld',
    },
)
