#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

ienv = agent.read_envfile("import.env")

for evar in [
        'HOSTNAME',
        'PROVISION_TYPE',
        'NBDOMAIN',
        'REALM',
        'IPADDRESS',
        'SVCUSER',
        'SVCPASS',
    ]:
    agent.set_env(evar, ienv[evar])
