#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import ipaddress

request = json.load(sys.stdin)

ienv = agent.read_envfile("import.env")

for evar in [
        'HOSTNAME',
        'PROVISION_TYPE',
        'NBDOMAIN',
        'REALM',
        'IPADDRESS',
        'SVCUSER',
        'SVCPASS',
    ]:
    agent.set_env(evar, ienv[evar])

with agent.redis_connect() as rdb:
    cluster_network = ipaddress.ip_network(rdb.get('cluster/network'))
if ipaddress.ip_address(ienv['IPADDRESS']) in cluster_network:
    # Required by Samba to bind interfaces without broadcast address:
    agent.set_env('PREFIXLEN', str(cluster_network.prefixlen))

agent.dump_env()
