#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

#
# Acquire all FSMO roles
#

podman exec -i samba-dc samba-tool fsmo transfer --role=all 1>&2
