#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

#
# Acquire all FSMO roles
#

exec 1>&2

request=$(cat /dev/stdin)
user=$(echo "$request" | jq -r '.adminuser // empty')
password=$(echo "$request" | jq -r '.adminpass // empty')
echo "$password" | podman exec -i samba-dc samba-tool fsmo transfer --role=all -U"$user"
