#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

podman_exec = ["podman", "exec", "samba-dc"]

request = json.load(sys.stdin)

# Check if the share already exists
pcheck = agent.run_helper(*(podman_exec + ["net", "conf", "showshare", request["name"]]))
if pcheck.returncode != 0:
    agent.set_status('validation-failed')
    json.dump([{'field':'name', 'parameter':'name','value': request['name'], 'error':'share_not_found'}], fp=sys.stdout)
    sys.exit(2)

samba_add_share = podman_exec + ["net", "conf", "setparm", request["name"]]

if 'description' in request:
    samba_add_share += ["comment", request["description"]]

phelper = agent.run_helper(*samba_add_share).check_returncode()
